name: testing fish shell
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up fish shell
        uses: fish-shop/install-fish-shell@v1
      - name: Run fish script
        shell: fish
        run: |
          echo "Hello, world!"
          fish --version
  test-bash:
    runs-on: ubuntu-latest
    steps:
      - name: Run bash script
        shell: bash
        run: |
          echo "Hello, world!"
          bash --version